services:
  java_app:
    build: practica_spring_boot/admin/admin
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://multitool_db:5432/postgres
      DB_USER: postgres      
      DB_PASS: 7894           
    restart: always
    depends_on:
      multitool_db:
        condition: service_healthy

  multitool_db:
    mem_limit: 512m
    image: postgres:14            
    ports:
      - "5432:5432"               
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: 7894      
      POSTGRES_DB: postgres        
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 10s
    volumes:
      - datos:/var/lib/postgresql/data

  angular-app:
    container_name: angular_app
    image: pee-angular_app:1.0.0
    build: ./multitools
    ports:
      - "4200:4200"
    depends_on:
      - java_app
    volumes:
    - node_modules:/app/node_modules

volumes:
  datos:
  node_modules:
