services:
  java_app:
    build: practica_spring_boot/admin/admin
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://multitool_db:5432/postgres
      DB_USER: postgres      
      DB_PASS: 7894           
    restart: always
    depends_on:
      multitool_db:
        condition: service_healthy
    entrypoint: ["dockerize", "-wait", "tcp://multitool_db:5432", "-timeout", "60s", "java", "-jar", "/path/to/your/app.jar"]
    networks:
      - multitool_network

  multitool_db:
    mem_limit: 512m
    image: postgres:14            
    ports:
      - "5433:5432"               
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: 7894      
      POSTGRES_DB: postgres        
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 20s
      timeout: 20s
      retries: 10
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - multitool_network

  angular-app:
    container_name: angular_app
    image: pee-angular_app:1.0.0
    build: ./multitools
    ports:
      - "4200:80"
    depends_on:
      - java_app
    volumes:
    - node_modules:/app/node_modules
    networks:
      - multitool_network
    restart: always

volumes:
  datos:
  node_modules:

networks:
  multitool_network:
    driver: bridge
