services:
  java_app:
    container_name: java_app
    build: practica_spring_boot/admin/admin
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://multitool_db:5432/postgres
      DB_USER: postgres      
      DB_PASS: 7894           
    restart: always
    depends_on:
      multitool_db:
        condition: service_healthy
    networks:
      - multitool_network

  multitool_db:
    container_name: db_app
    mem_limit: 256m
    image: postgres:17.4           
    ports:
      - "5433:5432"               
    environment:
      POSTGRES_USER: postgres    
      POSTGRES_PASSWORD: 7894      
      POSTGRES_DB: postgres        
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 20s
      timeout: 20s
      retries: 10
    volumes:
      - datos:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - multitool_network

  angular_app:
    container_name: angular_app
    image: pee-angular_app:1.0.0
    build: ./multitools
    ports:
      - "443:443"
    depends_on:
      - java_app
    volumes:
    - node_modules:/app/node_modules
    networks:
      - multitool_network
    restart: always

volumes:
  datos:
  node_modules:

networks:
  multitool_network:
    driver: bridge
