version: '3'

services:
  multitools:
    build: practica_spring_boot/admin/admin
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://multitool_db:5432/postgres?createDatabaseIfNotExist&serverTimezone=UTC
      DB_USER: postgres      
      DB_PASS: 7894           
    restart: always
    depends_on:
      multitool_db:
        condition: service_healthy

  multitool_db:
    image: postgres:14            
    ports:
      - "5432:5432"               
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: 7894      
      POSTGRES_DB: postgres        
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 10s
